version: '3.9'
services:
    db:
        image: mysql:8.0.31
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "${MYSQL_PORT}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - ./docker/db:/var/lib/mysql

    php:
        build:
            context: docker/php-fpm
            args:
                PHP_XDEBUG_MODE: ${PHP_XDEBUG_MODE}
                PHP_XDEBUG_CLIENT_PORT: ${PHP_XDEBUG_CLIENT_PORT}
                PHP_XDEBUG_CLIENT_HOST: ${PHP_XDEBUG_CLIENT_HOST}
                SYMFONY_CLI_VERSION: 4.27.4
        ports:
            - "${PHP_PORT}:9001"
        volumes:
            - ./:/var/www/symfony:cached
            - ./docker/logs/symfony:/var/www/symfony/var/log:cached
        depends_on:
            - db

    nginx:
        build: 
            context: docker/nginx
            args:
                NGINX_SYMFONY_SERVER_NAME: ${NGINX_SYMFONY_SERVER_NAME}
        ports:
            - "${NGINX_PORT}:80"
        depends_on:
            - php
        environment:
            - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/conf.d
            - NGINX_ENVSUBST_TEMPLATE_DIR=/etc/nginx/templates
            - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.template
            - NGINX_SYMFONY_SERVER_NAME=${NGINX_SYMFONY_SERVER_NAME}
        volumes:
            - ./docker/logs/nginx:/var/log/nginx:cached
            - ./:/var/www/symfony:cached
